apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sqctrl-ingress
  namespace: sqfaas
  annotations:
       nginx.ingress.kubernetes.io/rewrite-target: "/"
      #nginx.ingress.kubernetes.io/ssl-redirect: "true"
      #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx-private
  tls:
    - hosts:
      - sqctrl.sqfaas.dev
      secretName: ingress-tls
  rules:
    - host: sqctrl.sqfaas.dev
      http:
        paths:
          - path: /frontend
            pathType: Prefix
            backend:
              service:
                name: sqctrl-service
                port:
                  name: http
